# this is a temp file created for uploading Packing PO excel provided by deepak rana, should not be needed for final tool.

import sys
import os
import pandas as pd
from datetime import datetime


# --- PATH SETUP ---
current_dir = os.path.dirname(os.path.abspath(__file__))
project_root = os.path.dirname(current_dir)
if project_root not in sys.path:
    sys.path.insert(0, project_root)
from src import config, db

def parse_clean_dt(val):
    """Parses YYYY-MM-DD HH:MM:SS string from cleaned CSV."""
    if not val or str(val) == 'nan': return None
    try:
        return datetime.strptime(str(val).strip(), '%Y-%m-%d %H:%M:%S')
    except:
        return None


def main():
    print("--- UPLOADING CLEANED PACKING PO DATA TO SQL ---")

    # Read the CLEANED CSV (Generated by src/clean.py)
    file_path = os.path.join(config.INPUT_DIR, "PACKING_PO_DETAIL_Cleaned.csv")

    if not os.path.exists(file_path):
        print(f"Error: {file_path} not found.")
        print("Please run 'src/clean.py' first!")
        return

    print(f"Reading {file_path}...")
    df = pd.read_csv(file_path)

    conn = db.get_connection()
    if not conn:
        print("DB Connection Failed.")
        return

    cursor = conn.cursor()

    print("Re-creating table: packing_po...")
    cursor.execute("DROP TABLE IF EXISTS packing_po")
    cursor.execute("""
        CREATE TABLE packing_po (
            id INT AUTO_INCREMENT PRIMARY KEY,
            line VARCHAR(50),
            plan_plant_id VARCHAR(50),
            order_no VARCHAR(50),
            p_code VARCHAR(50),
            description VARCHAR(255),
            batch_no VARCHAR(50),
            start_datetime DATETIME,
            end_datetime DATETIME,
            planned_qty FLOAT,
            base_uom VARCHAR(20),
            load_utc_time DATETIME
        )
    """)

    data_to_insert = []

    for _, row in df.iterrows():
        try:
            # Parse Datetimes using helper
            # Note: clean.py has already separated Date and Time columns for Start/End
            # But kept load_utc_time as a full datetime string.

            # 1. Start Date + Time
            s_date = str(row.get('start_date', ''))
            s_time = str(row.get('start_time', ''))
            start_dt = None
            if s_date and s_date != 'nan':
                dt_str = f"{s_date} {s_time if s_time != 'nan' else '00:00:00'}"
                start_dt = parse_clean_dt(dt_str)

            # 2. End Date + Time
            e_date = str(row.get('End_date', ''))
            e_time = str(row.get('End_time', ''))
            end_dt = None
            if e_date and e_date != 'nan':
                dt_str = f"{e_date} {e_time if e_time != 'nan' else '00:00:00'}"
                end_dt = parse_clean_dt(dt_str)

            # 3. Load UTC Time (Already full string in CSV)
            load_dt = parse_clean_dt(row.get('load_utc_time'))

            if not start_dt:
                continue

            data_to_insert.append((
                str(row.get('Line', '')).strip(),
                str(row.get('plan_plant_id', '')),
                str(row.get('order_No', '')),
                str(row.get('P_Code', '')),
                str(row.get('Description', '')),
                str(row.get('batch_NO', '')),
                start_dt,
                end_dt,
                float(row.get('Planned_Quantity', 0)),
                str(row.get('base_uom', '')),
                load_dt  # <--- ENABLED
            ))

        except Exception as e:
            # print(f"Row Error: {e}")
            continue

    if data_to_insert:
        stmt = """
            INSERT INTO packing_po 
            (line, plan_plant_id, order_no, p_code, description, batch_no, start_datetime, end_datetime, planned_qty, base_uom, load_utc_time)
            VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
        """
        cursor.executemany(stmt, data_to_insert)
        conn.commit()
        print(f"Inserted {len(data_to_insert)} rows into packing_po table.")

    cursor.close()
    conn.close()
    print("Upload Complete.")


if __name__ == "__main__":
    main()